# Generated by Django 5.0.14 on 2026-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Packaging fee for Take-Out orders.', max_digits=10),
        ),
    ]
