# Server-only migration that existed on PythonAnywhere before the local
# branch was pushed. Added to the local repo so the migration graph is
# consistent across all environments.
# Generated by Django 4.2.16 on the PythonAnywhere server.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_migrate_queued_to_preparing'),
    ]

    operations = [
        # This was a server-side squash/alter that is already applied.
        # No operations needed — the schema state is captured in subsequent
        # migrations.
    ]
