# Generated by Django 4.2.16 on 2026-07-30 03:09
# Server-side merge migration added to local repo so the migration graph
# is consistent across all environments.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
        ('orders', '0006_convert_card_payments_to_cash'),
    ]

    operations = [
    ]
