# Generated by Django 6.0.4 on 2026-08-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the order was cancelled. Null for non-cancelled orders.', null=True),
        ),
    ]
