# Generated by Django 6.0.4 on 2026-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category_name',
            field=models.CharField(blank=True, default='', help_text="Snapshot of the product's category name at order time.", max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging_eligible',
            field=models.BooleanField(default=False, help_text="Snapshot: True when this item's category had is_packaging_required=True at order time. Used to recompute packaging fees for historical orders without reading live product/category data."),
        ),
    ]
