# Generated by Django 6.0.4 on 2026-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_category_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Order Sequence',
                'verbose_name_plural': 'Daily Order Sequences',
            },
        ),
    ]
