"""
Add Order.tracking_token — a cryptographically random, unique, URL-safe string
used as the public bearer credential for the customer-facing order tracker.

Why null=True initially
───────────────────────
Existing rows have no token yet.  We add the column as nullable first, then the
data migration (backfill_tracking_tokens) assigns a unique token to every
existing order, and finally we keep the column nullable so that any legacy code
path that bypasses Order.save() (direct ORM bulk operations, admin actions,
management commands) does not break.  New orders always receive a token through
Order.save(), which generates one whenever tracking_token is falsy.

Collision safety
────────────────
secrets.token_urlsafe(32) produces 43 URL-safe base64 characters, giving
~256 bits of entropy.  The probability of a collision across the entire
lifetime of the database is negligible.  The UNIQUE constraint is the
definitive guard; the loop below retries on the vanishingly unlikely event
that secrets.token_urlsafe produces a value that already exists.
"""
import secrets

from django.db import migrations, models


def backfill_tracking_tokens(apps, schema_editor):
    """Assign a unique tracking_token to every existing Order that lacks one.

    Fetches orders in batches of 500 so a large database does not hold a
    single massive transaction open.  Each token is generated by
    secrets.token_urlsafe(32), and a retry loop guards against the
    astronomically unlikely duplicate.
    """
    Order = apps.get_model('orders', 'Order')
    db = schema_editor.connection.alias

    # Collect PKs of orders that still need a token.
    pks = list(
        Order.objects.using(db)
        .filter(tracking_token__isnull=True)
        .values_list('pk', flat=True)
    )

    BATCH = 500
    for start in range(0, len(pks), BATCH):
        batch_pks = pks[start:start + BATCH]
        orders = Order.objects.using(db).filter(pk__in=batch_pks)
        for order in orders:
            # Retry until we land on a value not already in the database.
            while True:
                token = secrets.token_urlsafe(32)
                if not Order.objects.using(db).filter(tracking_token=token).exists():
                    break
            order.tracking_token = token
            order.save(update_fields=['tracking_token'])


def remove_tracking_tokens(apps, schema_editor):
    """Reverse: clear all tracking_token values (column drop handled by
    the schema operation below)."""
    # No-op: the RemoveField in migrations.operations handles the column.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_merge_server_and_local'),
    ]

    operations = [
        # 1. Add the column as nullable so existing rows are not affected.
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    'Server-generated cryptographically random token used for '
                    'the customer-facing order tracker URL. Cannot be predicted '
                    'from the order number, date, or any other public field.'
                ),
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        # 2. Backfill every existing order with a unique token.
        migrations.RunPython(
            backfill_tracking_tokens,
            reverse_code=remove_tracking_tokens,
        ),
    ]
