# Generated by Django 5.0.14 on 2026-06-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_packaging_required',
            field=models.BooleanField(default=False, help_text='Enable for meal/food categories. Adds packaging fee per item for Take-Out orders. Disable for beverages.'),
        ),
    ]
