# Generated by Django 5.0.14 on 2026-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_is_packaging_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When this product was soft-deactivated (is_active=False). Null while the product is active.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active products are sellable. Inactive (deactivated) products are hidden from the customer menu and the POS but are kept for historical records and can be reactivated at any time.'),
        ),
    ]
