# Generated by Django 5.2.17 on 2026-09-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('drink', 'Drink / Beverage'), ('food', 'Food / Meal'), ('other', 'Other')], default='other', help_text='Semantic type used by the AI chatbot to classify this category as a drink, food, or other. Independent of the packaging-fee flag — set both correctly.', max_length=10),
        ),
    ]
