# Generated by Django 5.0.14 on 2026-08-06 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('username', 'Username'), ('ip', 'IP address')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Failed login attempt',
                'verbose_name_plural': 'Failed login attempts',
            },
        ),
        migrations.AddConstraint(
            model_name='failedloginattempt',
            constraint=models.UniqueConstraint(fields=('scope', 'value'), name='unique_failed_login_scope_value'),
        ),
    ]
