# Generated by Django 5.0.14 on 2026-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_failedloginattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When this account was soft-deactivated (is_active=False). Null while the account is active.', null=True),
        ),
    ]
