# Generated by Django 6.0.4 on 2026-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image_filename',
            field=models.CharField(blank=True, default='', help_text='Original filename of the uploaded profile image (user-facing display only).', max_length=255),
        ),
    ]
