# Generated by Django 5.0.14 on 2026-07-29 09:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this cash reconciliation.', unique=True)),
                ('previous_coh', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening cash on hand for this day.', max_digits=12)),
                ('previous_coh_is_manual', models.BooleanField(default=False, help_text="True if previous COH was manually entered rather than auto-populated from yesterday's record.")),
                ('expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expenses_notes', models.TextField(blank=True, help_text='Description of expenses paid today.')),
                ('gcash_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total GCash order amounts (received digitally, not in cash drawer).', max_digits=12)),
                ('coins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coins set aside separately.', max_digits=12)),
                ('cash_advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash advances given to staff today.', max_digits=12)),
                ('floating_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Change float reserved for tomorrow.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Finance Record',
                'verbose_name_plural': 'Daily Finance Records',
                'ordering': ['-date'],
            },
        ),
    ]
