# Generated by Django 6.0.4 on 2026-09-17 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylog_product_snapshot'),
        ('menu', '0005_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('restock', 'Restock'), ('adjustment', 'Adjustment'), ('sale', 'Sale Deduction'), ('waste', 'Waste/Spoilage')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['action', '-created_at'], name='idx_invlog_action_created'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['product', '-created_at'], name='idx_invlog_product_created'),
        ),
    ]
